api_platform:
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  doctrine:
    enabled: true
  doctrine_mongodb_odm:
    enabled: false

  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header